### ISSUE TITLE
How do you stop it, when you want to work on a new project?[Issue]

### ISSUE THREAD

**Issue by axelmagnus** [johnwargo/circuitpython-sync#2]
So i like this a lot. But i have a question: how do you change the local folder that you want to sync to, that is, when i start a new cpy project? How long is the syncing active, forever or till you run it again in a new folder? is there a command to stop it from syncing?

Cheers, Axel

**Comment by johnwargo** [comment]
@axelmagnus did you read through the usage instructions?

Its a command-line utility. It synchronizes files from the CircuitPython device to the folder from where you launched the utility. To stop synchronizing, kill the command-line task (ctrl-C or terminate the terminal window). To sync to a different folder, open a terminal window to that folder and execute the command-line utility. 

No need to assign anyone to issues, this is my repository and I'm the only one in it, so I automatically get an email for every new issue or comment.

**Comment by axelmagnus** [comment]
allrlght, great. i didnt see this in the instructions, and i rarely use the terminal and basically dont know how that works. but now its clear, thanx. maybe you want to include this info in the instructions for us noobs.
